<?php declare(strict_types=1);
require_once './Page.php';

class Fahrer extends Page
{
    protected function __construct(){
        parent::__construct();
    }

    public function __destruct(){
        parent::__destruct();
    }

    protected function generateView():void{
        $ordered_article = $this->getViewData();
        $this->generatePageHeader('Fahrer','Seite.css');
        echo <<<EOT
    		<nav>
			<label class="logo">Alfredo</label>
			    <ul>
			      <li><a href="Bestellung.php">Bestellung</a></li>
			      <li><a href="Kunde.php">Kunde</a></li>
			      <li><a href="Baecker.php">Bäcker</a></li>
			      <li><a href="Fahrer.php">Fahrer</a></li>
			    </ul>
			</div>
	  </nav>
	  <section class="Bestellung">
		<header>
			<h1>Fahrer</h1>
		</header>
        <form id="myForm" action="Fahrer.php" accept-charset="utf-8" method="POST">
EOT;
        for($row = 0; $row < count($ordered_article); $row++){
            $ordered_article_id = htmlspecialchars($ordered_article[$row][0]);
            $orderingID = htmlspecialchars($ordered_article[$row][1]);
            $articleID = htmlspecialchars($ordered_article[$row][2]);
            $status = htmlspecialchars($ordered_article[$row][3]);
            $address = htmlspecialchars($ordered_article[$row][4]);
            $Pizza="";
            switch ($articleID){
                case 1:
                    $Pizza = "Salami";
                    break;
                case 2:
                    $Pizza = "Hawaii";
                    break;
                case 3:
                    $Pizza = "Margherita";
                    break;
                default:
                    break;
            }

            $group = $ordered_article_id;
            $legend = "Bestellung ".$orderingID." - Pizza ".$Pizza;
            $legend = htmlspecialchars($legend);
            $this->insert_ordered_article($legend,$group,$status,$address);
        }

        echo <<<EOT
        </form>
        </section>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script src="Fahrer.js"></script>
EOT;
        $this->generatePageFooter();
    }

    protected function getViewData():array{
        $ordered_article = array(array());
        $sqlselect = "Select ordered_article_id, o.ordering_id, article_id, status, address 
                        from ordered_article o, ordering od 
                        where status='3' AND o.ordering_id = od.ordering_id"; //status 3: Unterwegs
        $result = $this->database->query($sqlselect);
        $i = 0;
        if ($result->num_rows > 0) {
            // output data of each row
            while($row = $result->fetch_assoc()) {
                //var_dump($row);
                $ordered_article_id = $row["ordered_article_id"];
                $orderingID = $row["ordering_id"];
                $articleID = $row["article_id"];
                $status = $row["status"];
                $address = $row["address"];

                $ordered_article[$i][0] = $ordered_article_id;
                $ordered_article[$i][1] = $orderingID;
                $ordered_article[$i][2] = $articleID;
                $ordered_article[$i][3] = $status;
                $ordered_article[$i][4] = $address;
                $i++;
            }
            $result->free();
        }
        return $ordered_article;
    }

    private function insert_ordered_article($legend, $group, $status, $address){
        switch ($status){
            case 3:
                echo "<fieldset class='fieldset'>";
                echo "<legend>$legend</legend>";

                echo "<p> $address </p>";

                echo "<p><label for='Unterwegs'>Unterwegs</label>
                     <input type='radio' name=$group id='Unterwegs_radio' value='Unterwegs' onclick='myFunction(this)' checked></p>";

                echo "<p><label for='Geliefert'>Geliefert</label>
				<input type='radio' name=$group id='Geliefert_radio' value='Geliefert' onclick='myFunction(this)'><br></p>";
                echo "</fieldset>";
                break;
            case 4:
                echo "<fieldset class='fieldset'>";
                echo "<legend>$legend</legend>";

                echo "<p> $address </p>";

                echo "<p><label for='Unterwegs'>Unterwegs</label>
                     <input type='radio' name=$group id='Unterwegs_radio' value='Unterwegs' onclick='myFunction(this)'></p>";

                echo "<p><label for='Geliefert'>Geliefert</label>
				<input type='radio' name=$group id='Geliefert_radio' value='Geliefert' onclick='myFunction(this)' checked><br></p>";
                echo "</fieldset>";
                break;
                break;
            default:
                break;
        }
    }
    protected function processReceivedData(): void
    {
        parent::processReceivedData(); // TODO: Change the autogenerated stub
        if (isset($_POST['ordered_article_id']) && isset($_POST['status'])) {
            $status = -1;
            $ordered_article_id = $this->database->real_escape_string($_POST['ordered_article_id']); //ordered_article
            $value = $this->database->real_escape_string($_POST['status']);
            switch ($value){
                case 'Unterwegs':
                    $status = 3;
                    break;
                case 'Geliefert':
                    $status = 4;
                    break;
                default:
                    break;
            }
            if($status != -1) {
                $sql = "update ordered_article SET STATUS = ('$status') WHERE ordered_article_id = ('$ordered_article_id')";
                $this->database->query($sql);
            }
        }
    }

    public static function main():void{
        $Fahrer = new Fahrer();
        $Fahrer->processReceivedData();
        $Fahrer->generateView();
    }
}

Fahrer::main();