<?php
session_start();
require_once './Page.php';

class KundenStatus extends Page
{
    protected function __construct(){
        parent::__construct();
    }

    public function __destruct(){
        parent::__destruct();
    }

    protected function generateView():void{
        header("Content-Type: application/json; charset=UTF-8");
        $Array_mit_Daten_aus_Recordset = $this->getViewData();
        $serializedData = json_encode($Array_mit_Daten_aus_Recordset);
        echo $serializedData;
    }

    protected function getViewData():array
    {
        $ordered_article = array(array()); //my Array
        if (isset($_SESSION["BestellugnID"])) {
            $orderingID = $this->database->real_escape_string($_SESSION["BestellugnID"]);
            $sqlselect = "Select * from ordered_article where ordering_id='" . $orderingID . "'";
            $result = $this->database->query($sqlselect);
            $i = 0;
            if ($result->num_rows > 0) {
                // output data of each row
                while ($row = $result->fetch_assoc()) {
                    //var_dump($row);
                    $orderingID = $row["ordering_id"];
                    $articleID = $row["article_id"];
                    $status = $row["status"];
                    $ordered_article[$i][0] = $orderingID;
                    $ordered_article[$i][1] = $articleID;
                    $ordered_article[$i][2] = $status;
                    $i++;
                }
                $result->free();
            }
        }
        return $ordered_article;
    }

    protected function processReceivedData(): void
    {
        parent::processReceivedData(); // TODO: Change the autogenerated stub
    }

    public static function main():void{
        $KundeStatus = new KundenStatus();
        $KundeStatus->processReceivedData();
        $KundeStatus->generateView();
    }
}

KundenStatus::main();