<?php declare(strict_types=1);
require_once './Page.php';

class Fahrer extends Page
{
    protected function __construct(){
        parent::__construct();
    }

    public function __destruct(){
        parent::__destruct();
    }

    protected function generateView():void{
        $ordered_article = $this->getViewData();
        $this->generatePageHeader('Fahrer','Seite.css');
        echo <<<EOT
    		<nav>
			<label class="logo">Alfredo</label>
			    <ul>
			      <li><a href="Bestellung.php">Bestellung</a></li>
			      <li><a href="Kunde.php">Kunde</a></li>
			      <li><a href="Baecker.php">Bäcker</a></li>
			      <li><a href="Fahrer.php">Fahrer</a></li>
			    </ul>
			</div>
	  </nav>
	  <section class="Bestellung">
		<header>
			<h1>Fahrer</h1>
		</header>
EOT;
        $j = 1;
        for($row = 0; $row < count($ordered_article); $row++){
            $orderingID = htmlspecialchars($ordered_article[$row][0]);
            $articleID = htmlspecialchars($ordered_article[$row][1]);
            $status = htmlspecialchars($ordered_article[$row][2]);
            $Pizza="";
            switch ($articleID){
                case 1:
                    $Pizza = "Salami";
                    break;
                case 2:
                    $Pizza = "Hawaii";
                    break;
                case 3:
                    $Pizza = "Margherita";
                    break;
                default:
                    break;
            }

            $group = "group".$j;
            //var_dump($group);
            $legend = "Bestellung ".$orderingID." - Pizza ".$Pizza;
            $legend = htmlspecialchars($legend);
            $this->insert_ordered_article("fieldset",$legend,$group,(int)$status);
            $j++;
        }

        echo <<<EOT
        </section>
EOT;
        $this->generatePageFooter();
    }

    protected function getViewData():array{
        $ordered_article = array(array());
        $sqlselect = "Select * from ordered_article where status='3'"; //status 3: Unterwegs
        $result = $this->database->query($sqlselect);
        $i = 0;
        if ($result->num_rows > 0) {
            // output data of each row
            while($row = $result->fetch_assoc()) {
                //var_dump($row);
                $orderingID = $row["ordering_id"];
                $articleID = $row["article_id"];
                $status = $row["status"];
                $ordered_article[$i][0] = $orderingID;
                $ordered_article[$i][1]= $articleID;
                $ordered_article[$i][2] = $status;
                $i++;
            }
            $result->free();
        }
        return $ordered_article;
    }

    private function insert_ordered_article(string $fieldset, string $legend, string $group, int $status){
        switch ($status){
            case 3:
                echo "<fieldset class='$fieldset'>";
                echo "<legend>$legend</legend>";
                echo "<p><label for='Unterwegs'>Unterwegs</label>
                     <input type='radio' name=$group id='Unterwegs_radio' value='Unterwegs' checked></p>";

                echo "<p><label for='Geliefert'>Geliefert</label>
				<input type='radio' name=$group id='Geliefert_radio' value='Geliefert'><br></p>";
                echo "</fieldset>";
                break;
            case 4:
                echo "<fieldset class='$fieldset'>";
                echo "<legend>$legend</legend>";
                echo "<p><label for='Unterwegs'>Unterwegs</label>
                     <input type='radio' name=$group id='Unterwegs_radio' value='Unterwegs'></p>";

                echo "<p><label for='Geliefert'>Geliefert</label>
				<input type='radio' name=$group id='Geliefert_radio' value='Geliefert' checked><br></p>";
                echo "</fieldset>";
                break;
                break;
            default:
                break;
        }
    }
    protected function processReceivedData(): void
    {
        parent::processReceivedData(); // TODO: Change the autogenerated stub
    }

    public static function main():void{
        $Fahrer = new Fahrer();
        $Fahrer->processReceivedData();
        $Fahrer->generateView();
    }
}

Fahrer::main();